# Generated by Django 4.2 on 2025-02-04 07:07

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=task.models.Task.get_default_deadline),
        ),
    ]
