# Generated by Django 4.2 on 2025-02-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
