# Generated by Django 4.2 on 2025-02-04 08:15

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_detail_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=task.models.Task.get_default_deadline),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
