# Generated by Django 4.2 on 2025-02-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_deadline_alter_task_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
