# Generated by Django 4.2 on 2025-02-06 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='degree',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
