# Generated by Django 4.2 on 2025-02-06 04:55

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default=task.models.Task.get_default_deadline),
        ),
    ]
