# Generated by Django 4.2 on 2025-02-06 04:56

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=task.models.Task.get_default_deadline),
        ),
        migrations.AlterField(
            model_name='task',
            name='degree',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10),
        ),
    ]
