# Generated by Django 4.2 on 2025-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_deadline_alter_task_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='degree',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='high', max_length=10),
        ),
    ]
